spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barberia
    username: postgres
    password: 123321

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true

logging:
  level:
    com.barberia: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE